### ISSUE TITLE
Хватит паразитировать, пора использовать IPFS

### ISSUE THREAD

**Issue by asxcandrew** [femtoboard/nanoboard#27]
https://ru.wikipedia.org/wiki/IPFS
https://ipfs.io/
Дискас

**Comment by GrYlock** [comment]
http://imageboard.pe.hu/board.php?do=thread&id=61

**Comment by 13sqrt5** [comment]
Дело в том, что поиска по IPFS нет, как и по Freenet-у. Короче, нет возможности находить посты. Хранить-то можно, но все равно необходимо где-то хранить список этих самых постов, и обновлять его.

**Comment by femtoboard** [comment]
хватит искать подходящее p2p решение, наноборда отлично дружит с контейнерами, пора уже начать пользоваться
