### ISSUE TITLE
Не работает искаропки

### ISSUE THREAD

**Issue by alexmelyon** [femtoboard/nanoboard#28]
Пока не будет работать из коробки, не будет популяризации.
Вот скачал я последний релиз, заметил, что, внезапно, пароль обновился. Добавил мест из критичной Issue ветки. Итог: 3 поста - велком, категории и бред.
Что дальше то?

**Comment by 13sqrt5** [comment]
Кстати сказать, какой, собствено, пароль?

**Comment by vavopcartelera** [comment]
Все работало, джве недели назад. ПОЧИНИТЕ БЛЕАТЬ!

**Comment by alexmelyon** [comment]
@vavopcartelera Правда? http://imgur.com/a/szChk

**Comment by alexmelyon** [comment]
Это там из настроек поле "Password" пропало или мне показалось?

**Comment by 13sqrt5** [comment]
@alexmelyon У тебя в логах ~~черным по белому~~ белым по черному написано, что не удается найти капчапак. Ты его точно скачал и положил куда надо?

**Comment by femtoboard** [comment]
@alexmelyon закрываю issue, поскольку проблема явно в отсутствии капчепака
я мог бы заливать архивы вместе с капчепаком но это не совсем удобно (исполняемый файл меняется часто, капчапак - никогда, капчапак весит много, неудобно заливать, при обновлениях юзверям придется качать капчапак снова что неудобно и для юзверей)

**Comment by alexmelyon** [comment]
@femtoboard я правильно понимаю, что бинарники изменились (например пропало поле пароля), а исходники остались прежними и изменения не отобразились в коммитах?
Это очень плохо кагбэ.

**Comment by femtoboard** [comment]
понятия не имею куда делось поле пароля, сейчас разберусь, так быть не должно

**Comment by femtoboard** [comment]
@alexmelyon в общем суть такова:
дефолтный пароль зашит в код
если нужно распаковать контейнер -  из конфига берется пароль, если в конфиге пароля нет - туда записывается дефолтный пароль
а веб-интерфейс показывает то что есть в конфиге
поэтому сразу после запуска в веб-интерфейсе пароля видно не будет, а после первого сбора (collect) - поле с паролем появляется
это мелкий бажок, но если будет идти смена пароля (какой-нибудь форс мажор) то это будет мешать (придется вручную вписывать пароль в конфиг

**Comment by femtoboard** [comment]
@alexmelyon 
исправил этот баг, теперь пароль виден всегда
что касается соответствия кода и архива с релизом, они всегда соответствуют, поскольку сборка архива и заливка в репозиторий автоматизирована

**Comment by femtoboard** [comment]
добавил искаропочный вариант - один архив с капепаком, контейнерами и даже с базой
