### ISSUE TITLE
Как постить на наноборде?

### ISSUE THREAD

**Issue by Vlacovec** [femtoboard/nanoboard#30]
Прочитал ридми файл. Из него следует, что надо
> Вы можете писать посты, прикреплять картинки,
но чтобы ваши посты увидели другие,
вы должны создать PNG-контейнер и залить его
по одному из адресов которые можно найти
внизу любой страницы.

 > Нажмите [PNG-create] и в папке upload появится
новая PNG-картинка. Исходник для картинок
берётся из папки containers.

 > В контейнер влазит несколько последних постов
если они были текстовые или один-два поста
если они были с картинками (зависит от размера).
 Как минимум один последний пост туда точно входит.
 Входят туда также случайные посты других участников.

Мне нужно каждый раз жать пнг - криейт? И как понять что мой пост увидили другие люди? Если я буду заливать картинки их увидят другие? Поясните за постинг плис.

**Comment by femtoboard** [comment]
Привет, прочитай FAQ. Ты можешь написать несколько постов и нажать криейт, а потом уже постить последний файл из папки upload на одну из борд.

**Comment by 13sqrt5** [comment]
Да, тебе необходимо каждый раз жать PNG-create. Да, твои посты увидят остальные, но только после того как нажмут кнопку сбора постов, и если ты зальешь в один из тредов, посты из которых собираются нанобордой(есть внизу страницы). Как было замечено выше, не обязательно на каждый пост отправлять картинку-контейнер, можно написать несколько постов, и потом создать картинку-контейнер. Все посты туда влезут.
