### ISSUE TITLE
Кнопка collect png

### ISSUE THREAD

**Issue by Vlacovec** [femtoboard/nanoboard#33]
Сабж, кнопка проподает после ее нажатия, посты собираются и кнопка пропадает. Помогает только заход в settings, а потом обратно в main, кнопочка появляется. Это баг или фича?

**Comment by femtoboard** [comment]
Кнопка отключается на время сбора постов. Это фича. Заход в Settings просто сбрасывает состояние видимости кнопки. Кнопка сама появится когда сбор закончится. Сбор не может длиться вечно, если 30 секунд (время можно настроить в Settings), ничего не происходит с какой-то из загрузок - сбор прекращается и кнопка возвращается на место.

**Comment by Vlacovec** [comment]
Да, кстати. На античате есть тред, где обсуждается твоя борда. Вот https://forum.antichat.ru/threads/444846/#post-4017977
Есть сумневающиеся. Зарегайся, если ты еще не зарегался. И поясни всем что она охуенна. Ты же разраб и погромист. Я то простой юзверь. Заодно тред будет постоянно вверху, а это гарантировано что много народу узнает о нем. Оттуда много кто сидит на дваче. Думаю им будет интересна альтернатива.
На дваче есть тред, его можно побампать, но это я и сам могу https://2ch.hk/ch/res/5236.html

**Comment by Vlacovec** [comment]
> Кнопка отключается на время сбора постов. Это фича. Заход в Settings просто сбрасывает состояние видимости кнопки. Кнопка сама появится когда сбор закончится. Сбор не может длиться вечно, если 30 секунд (время можно настроить в Settings), ничего не происходит с какой-то из загрузок - сбор прекращается и кнопка возвращается на место.

А кнопка так и не появляется. Хотя проходит много времени.

**Comment by femtoboard** [comment]
Какая OS?
Какой список мест?
Клиент самый свежий, обновиться не предлагает?

**Comment by Vlacovec** [comment]
Mint
Так, список мест дефолтный
http://dobrochan.com/mad/res/75979.xhtml
http://sibirchan.ru/b/res/10656.html
http://volgach.ru/b/res/5226.html
http://02ch.su/b/res/7379.html
https://chaos.cyberpunk.us/st/50
https://endchan.xyz/test/res/971.html
https://xynta.ch/b/res/10540.html
https://www.nowere.net/wa/res/6271.html
https://alphachan.org/art/res/329789.html
https://hamstakilla.com/b/22279

Предлагает. Но я скачивал из репы, твоей, там вроде самая свежия версия.
Да, подскажи еще по обновлению. Там вроде нужно заменить несколько файлов и все? Напомни какие пожалуйста.

**Comment by femtoboard** [comment]
А как давно скачивал? Если предлагает значит не исключено, что у тебя версия старее.

Нужно заменить файлы:
scripts/*
pages/*
styles/*/*/*
nanodb.exe

Mint это ж вроде как линукс, попробуй воспользоваться воспользуйся установочно-обновительным [скриптом](https://github.com/femtoboard/nanoboard/releases/tag/3.0.11) просто кинь его на уровень выше чем твоя папка с нанобордой и запусти, он всё что надо обновит

**Comment by Vlacovec** [comment]
Спс, обновился. Стал получать новые посты. А то думал что сижу там один и никто не постит. А оказывается, что постинг идет во всю.
