### ISSUE TITLE
Замена капчи

### ISSUE THREAD

**Issue by LyBonyBon** [femtoboard/nanoboard#34]
Чтот я вообще не смог ввести эту капчу в новой обнове, посему хотел бы упомянуть о такой [ссылке](https://habrahabr.ru/post/121794/)

**Comment by femtoboard** [comment]
Капча Наноборды непривычна только поначалу. Это капча, к которой надо привыкнуть, потом будешь вводить на автомате.
Я чаще всего ввожу с одного раза. Вот только что навскидку:
<img width="85" alt="captcha" src="https://cloud.githubusercontent.com/assets/16354207/20647371/902dc6ca-b49b-11e6-83fb-f0cc505553fe.png">
вбил jkfnc с первого раза, не долго думая, и подошло.

потом сделал серию постов, ни разу не ошибся вводя капчу, вот скриншоты, все набранные ответы подошли:
<img width="85" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647402/6e63366e-b49c-11e6-9e4c-7c714211a602.png">
<img width="100" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647407/6e65ed3c-b49c-11e6-8e3b-35198685dd73.png">
<img width="79" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647404/6e646de0-b49c-11e6-8529-b53653fc06b4.png">
<img width="79" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647403/6e643a82-b49c-11e6-8a4a-230637474424.png">
<img width="82" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647406/6e648d84-b49c-11e6-8d93-24b70a154d4a.png">
<img width="80" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647405/6e648870-b49c-11e6-8cec-77c01ccef83e.png">
<img width="84" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647408/6e7aa1aa-b49c-11e6-9b01-1a8cc45a97b7.png">
<img width="79" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647409/6e7c1080-b49c-11e6-8a6b-92f29755ebd1.png">
<img width="78" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647413/6e7e1380-b49c-11e6-892c-401e91b3e30e.png">
<img width="80" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647411/6e7c7b1a-b49c-11e6-929c-8b10461103dd.png">
<img width="78" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647410/6e7c82b8-b49c-11e6-8a19-77b12c8c04b7.png">
<img width="81" alt="screen shot" src="https://cloud.githubusercontent.com/assets/16354207/20647414/6e927b68-b49c-11e6-89d3-29d81723231d.png">

А по ссылке описание слишком уж простой капчи, её будет просто сломать.
Сделать-то простую капчу не сложно (намного проще чем мудрёную). Когда готовилась капча я выставлял на обсуждение более простые варианты, их забраковали.

Пока что не вижу причин менять капчу на более простую, люди капчу вроде бы разобрали судя по отзывам, посты новые появляются регулярно. На более сложную - возможно, если эту сломают. Вообще смена капчи дело не простое. Это возможно, но есть нюансы. Пользователям нужно будет скачать новый капчепак и быть готовыми к тому, что посты из предыдущих контейнеров уже не будут распознаваться и старые посты не будут ретранслироваться. Поэтому вместе с обновлением капчепака придется поставлять и дамп базы до смены капчепака. В общем, это будут серьезные изменения, придется делать их организованно иначе могут остаться люди которые не обновились и вводят не ту капчу. Еще можно отключить капчу вообще (просто не валидировать подпись и всё, из защиты останется только POW) и повысить сложность POW, но ситуация будет похожая - предыдущие контейнеры получатся невалидными, придется сохранить дамп базы и давать его вместе с обновленным клиентом и обязательно уведомлять всех, чтобы обновились. Но опять же причин для этих действий пока нет.

**Comment by LyBonyBon** [comment]
Можно ведь ее усложнить, или-же просто сделать таймер сообщений на самом клиенте

**Comment by femtoboard** [comment]
Что значит таймер сообщений?

**Comment by LyBonyBon** [comment]
То есть после отправки 1 сообщения будет стоять таймер 15-30 секунд на след, сообщение

**Comment by femtoboard** [comment]
Ахах, нет, такие таймеры легко обходятся. Контейнер со спам-постами можно изготавливать вообще без клиента, на стороннем софте, не говоря уже о том, что исходный код клиента открыт и многое можно подправить вообще не перезапуская сервер. 
Вот уже есть POW и он уже заставляет ждать пару десятков секунд, иногда и дольше.

**Comment by LyBonyBon** [comment]
Тогда только аппаратную капчу пилить, инет говно и качать архив в 300мб тоже не очень прикольно)

**Comment by femtoboard** [comment]
Капчепак сейчас весит 117Мб если его качать отдельно в виде .xz архива (это 7zip/lzma).
Если у тебя интернет говняный, то это надо исправлять, потому что ты ни обновления безопасности на свою ОС не сможешь качать, ни ПНГ-контейнеры собирать (тут поболее 300Мб в день может выходить когда людей наберется человек, скажем, 100), ни через Тор картинки заливать нормально, в общем криптоанархист из тебя будет скверный.

**Comment by LyBonyBon** [comment]
Это временно, но на данный момент стоит подумать о такой капче

**Comment by femtoboard** [comment]
О какой капче, подробнее, плиз

**Comment by LyBonyBon** [comment]
На хабре описано и расписано

**Comment by LyBonyBon** [comment]
Пользуйся)

**Comment by femtoboard** [comment]
Опиши какие преимущества эта капча будет иметь перед текущей?

**Comment by LyBonyBon** [comment]
Меньше вес, более понятная

**Comment by femtoboard** [comment]
сколько будет весить одна такая капча, как ты думаешь?

**Comment by LyBonyBon** [comment]
Это мелкий код, а не целая база пикч, ты совсем двинулся?

**Comment by femtoboard** [comment]
И как, по-твоему, людям преподнести этот мелкий код да так, чтобы они им не воспользовались для обхода капчи?

**Comment by LyBonyBon** [comment]
Достаточно запутать код как это сделала денува)

**Comment by femtoboard** [comment]
Всё что запутано, может быть и распутано. К тому же из всего клубка будут нужны только пару мест, где происходит проверка. Это ни разу не надёжно. Да и смысла УПРОЩАТЬ капчу не вижу, это упростит работу распознавальщикам да и всё.

**Comment by femtoboard** [comment]
Что же касается кода, то код и у меня есть, ведь эту капчу генерировал я, так что мне не особо нужны чьи-то костыли на PHP, чтобы сделать свою капчу на клиенте. Уникальность моей капчи в том, что разгадка нигде не фигурирует в данных, несмотря на то, что у всех имеется капчепак, а код и SEED генерации тоже недоступны (и это нормально, я же не прошу никого запускать какой-то мутный бинарник или запутанный код). Ключ ЭЦП зашифрован разгадкой, этим ключом подписывается пост, прошедший POW. От хэша POW зависит номер капчи из капчепака. Подобрать себе определенную капчу будет в миллион раз дольше чем прохождение одного POW. Есть незашифрованный публичный ключ, которым проверяется подпись, и от которого больше никакого проку. Если разгадка правильная - подпись подтверждается. Эту проверку производит клиент с каждым входящим постом - берет нужную капчу, сверяет подпись. Сама подпись тоже не несёт в себе разгадки, задействовать её как-то еще не получится. 
А просто генерировать капчу на клиенте это смешно. К тому же за обфускацию или за, чего хуже - мутные бинарники, спасибо не скажут, это опен-сорс. Поэтому файлик с данными - отличный компромисс, невзламываемый никак кроме брут-форса (быстрее распознавать вручную, хотя КУДА может ускорить процесс, но усилий по написанию брутилки придется приложить немало).

**Comment by LyBonyBon** [comment]
Нахрена тогда юзать это говно? Оно не юзабельно из-за этой капчи, делай другую

**Comment by femtoboard** [comment]
Иди нахуй, сам ты говно, капча охуенна, люди пользуются, один ты не смог осилить, пойди сделай свою борду и занимайся там ерундой типа бессмысленной генерации идеально читаемой капчи на клиенте.

**Comment by Vlacovec** [comment]
Не слушай никого, капча охуительная. Я тоже не могу в нее с первого раза, но похуй. Куда торопиться то? Только хардкор. Да хуй завайпаешь. Ничего не меняй.

**Comment by 13sqrt5** [comment]
Есть тут и здравое зерно, на мой взгляд. Сейчас капчапак у нас достаточно большой, некоторые жалуются. Думаю, можно его сильно уменьшить, если оптимизировать формат хранения картинок внутри капчапака. Вот эта штука: https://en.wikipedia.org/wiki/Run-length_encoding выглядит многообещающе применительно к нашему случаю. Сравнительно просто в реализации, и в то же время должно довольно сильно ужать.

**Comment by femtoboard** [comment]
Я применил LZMA, он похитрее RLE будет, сжал со 189 (125 байт из них - битовая картинка) до 117Мб, то есть 117 байт на одну капчу (наверняка сжались именно картинки ведь в ключах слишком много энтропии), сейчас этот 117Мб-файл и скачивается установочным скриптом.
RLE если бы и помог как-то в размере, то усложнил бы чтение капчи и добавил бы лишнего в заголовок капчепака (пришлось бы смещения записывать и размеры).

**Comment by 13sqrt5** [comment]
Хм. Действительно. Пережимать целиком капчапак перед закачкой-тоже вариант.
